export const mockWorkspace = {
  id: "ws-1",
  name: "Global Agency",
  plan: "Pro Plan",
  minutesUsed: 1440,
  minutesIncluded: 2000,
  daysRemaining: 8,
  overageRate: 0.05,
};

export const mockAgents = [
  {
    id: "agent-1",
    name: "Agent Support FR",
    isActive: true,
    totalCalls: 1284,
    avgDuration: "3:42",
    voiceId: "Cartesia — Gabriel",
    color: "from-primary to-secondary",
    publishedAt: "12 jan. 2026",
  },
  {
    id: "agent-2",
    name: "Sales Assistant",
    isActive: true,
    totalCalls: 856,
    avgDuration: "2:15",
    voiceId: "Cartesia — Sophie",
    color: "from-secondary to-tertiary",
    publishedAt: "3 fév. 2026",
  },
  {
    id: "agent-3",
    name: "Knowledge Bot",
    isActive: false,
    totalCalls: 412,
    avgDuration: "5:08",
    voiceId: "ElevenLabs — Marie",
    color: "from-tertiary to-primary",
    publishedAt: "28 mars 2026",
  },
  {
    id: "agent-4",
    name: "Rappel Campagne",
    isActive: true,
    totalCalls: 2100,
    avgDuration: "1:30",
    voiceId: "Cartesia — Gabriel",
    color: "from-primary/80 to-error/60",
    publishedAt: "1 avr. 2026",
  },
];

export const mockConversations = [
  {
    id: "conv-1",
    callerNumber: "+33 6 12 •••• 89",
    agentName: "Agent Support FR",
    agentColor: "bg-tertiary",
    duration: "04:12",
    status: "success" as const,
    statusLabel: "Succès",
    date: "Aujourd'hui, 14:24",
    type: "inbound" as const,
    typeLabel: "Entrant",
    sentiment: "positive" as const,
    isBilled: true,
    transcript: [
      { role: "agent", content: "Bonjour, vous êtes bien chez Callpme, comment puis-je vous aider ?", ts: "14:20:01" },
      { role: "user", content: "Oui bonjour, j'aimerais savoir comment configurer mon agent.", ts: "14:20:08" },
      { role: "agent", content: "Bien sûr ! Pour configurer votre agent, rendez-vous dans la section Agents de votre tableau de bord.", ts: "14:20:15" },
    ],
    summary: "L'utilisateur souhaitait comprendre comment configurer son agent IA. L'agent a fourni les instructions de navigation vers la section Agents.",
  },
  {
    id: "conv-2",
    callerNumber: "+33 7 88 •••• 12",
    agentName: "Sales Assistant",
    agentColor: "bg-primary",
    duration: "01:45",
    status: "success" as const,
    statusLabel: "Succès",
    date: "Aujourd'hui, 13:05",
    type: "inbound" as const,
    typeLabel: "Entrant",
    sentiment: "positive" as const,
    isBilled: true,
    transcript: [
      { role: "agent", content: "Bonjour ! Sales Assistant à votre service.", ts: "13:04:00" },
      { role: "user", content: "Je voulais avoir des infos sur vos tarifs.", ts: "13:04:07" },
    ],
    summary: "Demande de renseignements sur les tarifs. Prospect qualifié, intérêt confirmé.",
  },
  {
    id: "conv-3",
    callerNumber: "+33 6 45 •••• 67",
    agentName: "Agent Support FR",
    agentColor: "bg-tertiary",
    duration: "00:30",
    status: "missed" as const,
    statusLabel: "Manqué",
    date: "Hier, 18:42",
    type: "inbound" as const,
    typeLabel: "Entrant",
    sentiment: "neutral" as const,
    isBilled: false,
    transcript: [],
    summary: "Appel manqué, aucun message laissé.",
  },
  {
    id: "conv-4",
    callerNumber: "+33 1 23 •••• 90",
    agentName: "Knowledge Bot",
    agentColor: "bg-secondary",
    duration: "12:54",
    status: "success" as const,
    statusLabel: "Succès",
    date: "Hier, 16:15",
    type: "outbound" as const,
    typeLabel: "Sortant",
    sentiment: "positive" as const,
    isBilled: true,
    transcript: [
      { role: "agent", content: "Bonjour, je vous contacte au sujet de votre demande.", ts: "16:14:10" },
      { role: "user", content: "Ah oui, bonjour !", ts: "16:14:18" },
    ],
    summary: "Appel sortant réussi. Client satisfait, problème résolu.",
  },
  {
    id: "conv-5",
    callerNumber: "+33 6 78 •••• 34",
    agentName: "Sales Assistant",
    agentColor: "bg-primary",
    duration: "02:10",
    status: "interrupted" as const,
    statusLabel: "Interrompu",
    date: "Hier, 11:30",
    type: "inbound" as const,
    typeLabel: "Entrant",
    sentiment: "negative" as const,
    isBilled: false,
    transcript: [
      { role: "agent", content: "Bonjour, bienvenue !", ts: "11:29:50" },
      { role: "user", content: "Je veux parler à quelqu'un.", ts: "11:29:58" },
    ],
    summary: "Appel interrompu, l'appelant souhaitait un agent humain.",
  },
];

export const mockCampaigns = [
  {
    id: "camp-1",
    name: "Relance Prospects Avril",
    agentName: "Sales Assistant",
    status: "active" as const,
    statusLabel: "Active",
    totalContacts: 150,
    calledCount: 87,
    successCount: 62,
    scheduledAt: "Démarré le 8 avr.",
    callWindowStart: "09:00",
    callWindowEnd: "18:00",
  },
  {
    id: "camp-2",
    name: "Rappel RDV Clients",
    agentName: "Agent Support FR",
    status: "paused" as const,
    statusLabel: "En pause",
    totalContacts: 45,
    calledCount: 23,
    successCount: 19,
    scheduledAt: "Démarré le 5 avr.",
    callWindowStart: "10:00",
    callWindowEnd: "17:00",
  },
  {
    id: "camp-3",
    name: "Campagne Onboarding",
    agentName: "Knowledge Bot",
    status: "completed" as const,
    statusLabel: "Terminée",
    totalContacts: 80,
    calledCount: 80,
    successCount: 71,
    scheduledAt: "Terminé le 1 avr.",
    callWindowStart: "09:00",
    callWindowEnd: "19:00",
  },
];

export const mockKnowledgeBases = [
  {
    id: "kb-1",
    name: "FAQ Produit",
    mode: "full_context" as const,
    modeLabel: "Full Context",
    files: ["faq-produit.pdf", "guide-utilisateur.docx"],
    fileCount: 2,
    createdAt: "12 jan. 2026",
  },
  {
    id: "kb-2",
    name: "Documentation Technique",
    mode: "rag" as const,
    modeLabel: "RAG",
    files: ["api-docs.pdf", "integration-guide.pdf", "webhooks.txt"],
    fileCount: 3,
    createdAt: "28 mars 2026",
  },
];

export const mockPhoneNumbers = [
  {
    id: "num-1",
    number: "+33 1 87 XX XX XX",
    provider: "sip_trunk",
    trunkName: "Trunk Principal FR",
    friendlyName: "Numéro Support",
    isActive: true,
    assignedAgent: "Agent Support FR",
  },
  {
    id: "num-2",
    number: "+33 7 56 XX XX XX",
    provider: "sip_trunk",
    trunkName: "Trunk Principal FR",
    friendlyName: "Numéro Sales",
    isActive: true,
    assignedAgent: "Sales Assistant",
  },
  {
    id: "num-3",
    number: "+33 9 72 XX XX XX",
    provider: "sip_trunk",
    trunkName: "Trunk Backup",
    friendlyName: "Numéro Backup",
    isActive: false,
    assignedAgent: null,
  },
];

export const mockApiTokens = [
  {
    id: "tok-1",
    name: "Production API",
    prefix: "cmp_prod_xxxx",
    lastUsed: "Il y a 2 minutes",
    createdAt: "1 jan. 2026",
  },
  {
    id: "tok-2",
    name: "Integration CRM",
    prefix: "cmp_crm_xxxx",
    lastUsed: "Il y a 3 heures",
    createdAt: "15 fév. 2026",
  },
];

export const mockWebhooks = [
  {
    id: "wh-1",
    url: "https://mon-crm.fr/webhook/callpme",
    events: ["call.started", "call.ended"],
    isActive: true,
    lastTriggered: "Il y a 5 min",
    lastStatus: 200,
  },
];

export const mockBillingCycles = [
  {
    id: "cycle-1",
    period: "Avr. 2026",
    cycleStart: "1 avr.",
    cycleEnd: "30 avr.",
    minutesIncluded: 2000,
    minutesUsed: 1440,
    minutesOverage: 0,
    amountBase: 149,
    amountOverage: 0,
    amountTotal: 149,
    status: "open" as const,
    statusLabel: "Ouvert",
  },
  {
    id: "cycle-2",
    period: "Mars 2026",
    cycleStart: "1 mars",
    cycleEnd: "31 mars",
    minutesIncluded: 2000,
    minutesUsed: 2156,
    minutesOverage: 156,
    amountBase: 149,
    amountOverage: 7.8,
    amountTotal: 156.8,
    status: "paid" as const,
    statusLabel: "Payé",
  },
  {
    id: "cycle-3",
    period: "Fév. 2026",
    cycleStart: "1 fév.",
    cycleEnd: "28 fév.",
    minutesIncluded: 2000,
    minutesUsed: 1890,
    minutesOverage: 0,
    amountBase: 149,
    amountOverage: 0,
    amountTotal: 149,
    status: "paid" as const,
    statusLabel: "Payé",
  },
];

export const mockStats = {
  minutesUsed: 1284,
  minutesRemaining: 716,
  totalCalls: 4812,
  answerRate: 92.4,
  minutesTrend: +12,
  callsTrend: +24,
  answerTrend: -3,
};
